log4j:WARN No appenders could be found for logger (org.openspaces.core.space.UrlSpaceFactoryBean).
log4j:WARN Please initialize the log4j system properly.
2015-04-18 18:49:09,461  INFO [net.jini.lookup.ServiceDiscoveryManager] - Exception occurred during query, discarding reggie [com.sun.jini.reggie.RegistrarProxy[registrar=0575c7b1-5db8-4b54-abd0-ba5674d30afc DynamicSmartStub [ImplObjClass: com.sun.jini.reggie.GigaRegistrar, ConnectionURL: NIO://kafka.local:53309/pid[35458]/1429346479421803232_2_639148318494860921_details[class com.sun.jini.reggie.GigaRegistrar], MaxConnPool: 1024 ]]]; Caused by: java.rmi.ConnectException: Connect Failed to [NIO://kafka.local:53309/pid[35458]/1429346479421803232_2_639148318494860921_details[class com.sun.jini.reggie.GigaRegistrar]]; nested exception is: 
	java.net.ConnectException: Connection refused
2015-04-18 18:49:14,229  INFO [net.jini.lookup.ServiceDiscoveryManager] - Exception occurred during query, discarding reggie [com.sun.jini.reggie.RegistrarProxy[registrar=0575c7b1-5db8-4b54-abd0-ba5674d30afc DynamicSmartStub [ImplObjClass: com.sun.jini.reggie.GigaRegistrar, ConnectionURL: NIO://kafka.local:53309/pid[35458]/1429346479421803232_2_639148318494860921_details[class com.sun.jini.reggie.GigaRegistrar], MaxConnPool: 1024 ]]]; Caused by: java.rmi.ConnectException: Connect Failed to [NIO://kafka.local:53309/pid[35458]/1429346479421803232_2_639148318494860921_details[class com.sun.jini.reggie.GigaRegistrar]]; nested exception is: 
	java.net.ConnectException: Connection refused
2015-04-18 18:49:14,656  INFO [net.jini.lookup.ServiceDiscoveryManager] - Exception occurred while attempting to register with the lookup service event mechanism; Caused by: java.rmi.ConnectException: Connect Failed to [NIO://kafka.local:53309/pid[35458]/1429346479421803232_2_639148318494860921_details[class com.sun.jini.reggie.GigaRegistrar]]; nested exception is: 
	java.net.ConnectException: Connection refused
2015-04-18 18:49:19,579  INFO [net.jini.lookup.ServiceDiscoveryManager] - Exception occurred while attempting to register with the lookup service event mechanism; Caused by: java.rmi.ConnectException: Connect Failed to [NIO://kafka.local:53309/pid[35458]/1429346479421803232_2_639148318494860921_details[class com.sun.jini.reggie.GigaRegistrar]]; nested exception is: 
	java.net.ConnectException: Connection refused
2015-04-18 18:49:24,581  INFO [net.jini.lookup.ServiceDiscoveryManager] - Exception occurred while attempting to register with the lookup service event mechanism; Caused by: java.rmi.ConnectException: Connect Failed to [NIO://kafka.local:53309/pid[35458]/1429346479421803232_2_639148318494860921_details[class com.sun.jini.reggie.GigaRegistrar]]; nested exception is: 
	java.net.ConnectException: Connection refused
2015-04-18 18:49:29,582  INFO [net.jini.lookup.ServiceDiscoveryManager] - Exception occurred while attempting to register with the lookup service event mechanism; Caused by: java.rmi.ConnectException: Connect Failed to [NIO://kafka.local:53309/pid[35458]/1429346479421803232_2_639148318494860921_details[class com.sun.jini.reggie.GigaRegistrar]]; nested exception is: 
	java.net.ConnectException: Connection refused
2015-04-18 18:49:34,584  INFO [net.jini.lookup.ServiceDiscoveryManager] - Exception occurred while attempting to register with the lookup service event mechanism; Caused by: java.rmi.ConnectException: Connect Failed to [NIO://kafka.local:53309/pid[35458]/1429346479421803232_2_639148318494860921_details[class com.sun.jini.reggie.GigaRegistrar]]; nested exception is: 
	java.net.ConnectException: Connection refused
2015-04-18 18:49:39,585  INFO [net.jini.lookup.ServiceDiscoveryManager] - Exception occurred while attempting to register with the lookup service event mechanism; Caused by: java.rmi.ConnectException: Connect Failed to [NIO://kafka.local:53309/pid[35458]/1429346479421803232_2_639148318494860921_details[class com.sun.jini.reggie.GigaRegistrar]]; nested exception is: 
	java.net.ConnectException: Connection refused
2015-04-18 18:49:43,613  INFO [net.jini.discovery.LookupDiscovery] - exception occurred during unicast discovery to kafka.local:4174 with constraints InvocationConstraints[reqs: {}, prefs: {}]; Caused by: java.net.ConnectException: Connection refused
2015-04-18 18:49:43,615  INFO [net.jini.discovery.LookupDiscovery] - exception occurred during unicast discovery to kafka.local:4174 with constraints InvocationConstraints[reqs: {}, prefs: {}]; Caused by: java.net.ConnectException: Connection refused
2015-04-18 18:49:44,585  INFO [net.jini.lookup.ServiceDiscoveryManager] - Exception occurred while attempting to register with the lookup service event mechanism; Caused by: java.rmi.ConnectException: Connect Failed to [NIO://kafka.local:53309/pid[35458]/1429346479421803232_2_639148318494860921_details[class com.sun.jini.reggie.GigaRegistrar]]; nested exception is: 
	java.net.ConnectException: Connection refused
